#!/bin/bash

# Script para desplegar en Render
# Este script describe los pasos para desplegar los servicios en Render

echo "=== RAG Internal Assistant - Render Deployment Setup ==="
echo ""
echo "Este script asume que ya tienes:"
echo "1. Código en GitHub"
echo "2. Cuenta en Render.com"
echo "3. Frontend ya desplegado en Vercel"
echo ""

echo "PASO 1: Crear MCP Server en Render"
echo "=================================="
echo "1. Ve a https://dashboard.render.com"
echo "2. Click en 'New +' → 'Web Service'"
echo "3. Conecta tu repositorio GitHub"
echo "4. Completa la siguiente información:"
echo ""
echo "   Name: rag-mcp-server"
echo "   Runtime: Node"
echo "   Root Directory: apps/mcp-server"
echo "   Build Command: pnpm install && pnpm build"
echo "   Start Command: pnpm start"
echo ""
echo "5. Bajo 'Advanced' → 'Add Environment Variable'"
echo "   NODE_ENV = production"
echo "   MCP_API_KEY = (tu api key segura)"
echo "   N8N_WEBHOOK_URL = (tu webhook de n8n)"
echo ""

echo "PASO 2: Crear Python Backend en Render"
echo "======================================"
echo "1. Click en 'New +' → 'Web Service'"
echo "2. Conecta tu repositorio GitHub"
echo "3. Completa la siguiente información:"
echo ""
echo "   Name: rag-python-backend"
echo "   Runtime: Python 3"
echo "   Root Directory: services"
echo "   Build Command: pip install -r requirements.txt"
echo "   Start Command: uvicorn src.main:app --host 0.0.0.0 --port 8000"
echo ""
echo "4. Bajo 'Advanced' → 'Add Environment Variable'"
echo "   ENVIRONMENT = production"
echo "   PYTHONUNBUFFERED = 1"
echo "   GROQ_API_KEY = (tu groq api key)"
echo "   CHROMA_DB_PATH = /tmp/chroma_db"
echo ""

echo "PASO 3: Actualizar URLs en Vercel"
echo "=================================="
echo "1. Ve a tu proyecto en Vercel"
echo "2. Settings → Environment Variables"
echo "3. Actualiza:"
echo ""
echo "   NEXT_PUBLIC_MCP_SERVER_URL = https://rag-mcp-server.onrender.com"
echo "   NEXT_PUBLIC_API_URL = https://rag-python-backend.onrender.com"
echo ""
echo "4. Redeploy el frontend"
echo ""

echo "VERIFICACIÓN"
echo "============"
echo "✓ MCP Server salud: https://rag-mcp-server.onrender.com/health"
echo "✓ Python Backend: https://rag-python-backend.onrender.com/docs"
echo "✓ Frontend: Tu URL de Vercel"
echo ""
echo "¡Deployment completado!"
