import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { NavBar } from "./_components/NavBar";
import { theme } from "./_config/theme";
import { Footer } from "./_components/Footer";
import { ConversationContext, useConversationContext } from "@/context";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  //const conversationId = useConversationContext();
  return (
    <html lang="en">
      <body
        className={`antialiased flex flex-col h-screen ${geistSans.variable} ${geistMono.variable}`}
      >
        <NavBar />

        <main className="flex-1 h-full">{children}</main>

        <Footer />
      </body>
    </html>
  );
}
