import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { NavBar } from "./_components/NavBar";
import { Footer } from "./_components/Footer";
import { ChatProvider } from "@/providers/ChatProvider";
import { ReactNode } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function RootLayoutContent({ children }: { children: ReactNode }) {
  // Import usePathname inside component to use client-side routing
  const pathname = require("next/navigation").usePathname?.();
  const isHomePage = pathname === "/";
  const isChatPage = pathname?.includes("/chat");

  return (
    <>
      <NavBar />
      <ChatProvider>
        <main
          className={`flex-1 min-h-0 ${
            isChatPage ? "overflow-hidden" : "overflow-y-auto"
          }`}
        >
          {children}
        </main>
      </ChatProvider>
      {isHomePage && <Footer />}
    </>
  );
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body
        className={`antialiased flex flex-col h-full overflow-hidden ${geistSans.variable} ${geistMono.variable}`}
      >
        <RootLayoutContent>{children}</RootLayoutContent>
      </body>
    </html>
  );
}
